version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      # - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      # - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGODB_DATABASE
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
    networks:
      - graphql-app
      
  app:
    depends_on:
      - mongodb
    build: ./graphqlapp
    restart: unless-stopped
    env_file: ./graphqlapp/.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true
    networks:
      - graphql-app

volumes:
  db:

networks:
  graphql-app:
    driver: bridge